'use strict';
const $=id=>document.getElementById(id),C=window.WW_CONTENT,M=window.WWModel;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modes={none:'No harvest',random:'Random capture',large:'Larger fish more likely'},foods={low:'Low',normal:'Normal',high:'High'};
let storageOK=true;function readStore(k,fallback){try{return JSON.parse(localStorage.getItem('ww-v1-'+k))??fallback;}catch(e){storageOK=false;return fallback;}}function store(k,v){try{localStorage.setItem('ww-v1-'+k,JSON.stringify(v));}catch(e){storageOK=false;$('storageNotice').textContent='Browser storage is unavailable or full. Download your notebook and runs before leaving.';}}
let notes=readStore('notes',{}),saved=readStore('runs',[]),plan=readStore('plan',[]);if(!Array.isArray(saved))saved=[];if(!notes||typeof notes!=='object')notes={};
let model=new M.Model(),chapter=0,timer=null,selected=null,visuals=[],motionPaused=matchMedia('(prefers-reduced-motion: reduce)').matches;
const fishSVG=`<svg viewBox="0 0 120 45" aria-hidden="true"><path fill="#b2a34c" d="M28 22L4 6 8 23 3 39 29 25Z"/><path fill="#778254" d="M46 15L51 2 56 12 62 3 68 14 78 6 84 16Z"/><path fill="#dbcf88" d="M24 23Q48 5 89 15L113 23Q83 43 44 31Z"/><path fill="#64724c" d="M24 23Q49 9 88 15L112 23Q75 21 26 25Z"/><path fill="#a99850" d="M60 29L73 40 77 28Z"/><path fill="none" stroke="#526347" stroke-width="1.5" d="M90 17Q84 25 90 31M32 24Q58 19 84 24"/><circle fill="#171f20" cx="99" cy="21" r="3.3"/><circle fill="#fff6c7" cx="100" cy="20" r="1.1"/><path fill="#f4eecf" d="M9 34L4 39 21 30Z"/></svg>`;
const lake=`<div class="hero"><a href="assets/lake-map.svg" target="_blank" rel="noopener" aria-label="Open the lake map at full size"><img class="lake-map" src="assets/lake-map.svg" alt="Mistassini Lake extends northeast from Mistissini. Takwa is in the north; Chalifour, Perch, and Icon cluster near the southern end."></a><div class="hero-caption"><strong>People → observations → questions → continuing investigation</strong><br>Place-based knowledge helps determine what to ask, where to look, and why the answer matters.</div></div>`;
const riverData=window.WW_READINGS.river;
const evidenceOptions=[['Community observations','Work with consenting knowledge holders to decide which changes, locations, and histories matter. Agree on what may be recorded or shared.'],['Length and mass','Use consistent gear, season, sites, and sex categories to compare body-size distributions.'],['Age and growth','Use comparable, validated aging methods to separate age structure from growth differences.'],['Water, food, and habitat','Track environmental conditions alongside growth to test environmental explanations.'],['Harvest information','Collaboratively document effort, methods, and catches across relevant fisheries; avoid blaming a group from indirect evidence.'],['Genetic samples','With appropriate permissions, compare carefully filtered samples across times and sites to test gene-pool change.']];
function renderChapter(){const c=C[chapter];$('tag').textContent=c.label;$('tag').className='tag'+(c.label==='Teaching model'?' model':'');$('progress').textContent=`0${chapter+1} / 07`;$('chapterTitle').textContent=c.title;$('subtitle').textContent=c.subtitle;
$('chapters').innerHTML=C.map((x,i)=>`<button class="chapter-link ${i===chapter?'active':''}" data-ch="${i}" aria-label="${i+1}. ${esc(x.title)}" ${i===chapter?'aria-current="step"':''}><span class="num">${i+1}</span><span class="chname">${esc(x.title)}</span></button>`).join('');document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>go(+b.dataset.ch));
const paragraphs=c.body.map(p=>`<p>${esc(p)}</p>`);$('reading').innerHTML=paragraphs.slice(0,2).join('')+(paragraphs.length>2?`<details><summary>${chapter===0?'How the investigation unfolded':'Read the investigation steps'}</summary>${paragraphs.slice(2).join('')}</details>`:'');
$('special').innerHTML='';$('lab').hidden=!(chapter>=2&&chapter<=4);
if(chapter===0)$('special').innerHTML=lake+`<blockquote>“${esc(c.quote)}”<cite>${esc(c.quoteBy)} <button class="linkbutton" data-open-box>Read Box 1</button></cite></blockquote><div class="twocol"><section class="panel"><h3>Knowledge that shapes the inquiry</h3><p>Read the research summary above and MacLeod’s account in Box 1. Identify who noticed the change, what they knew about the fishery, and what they wanted to learn.</p><p class="small">The 17 interviewees were knowledgeable participants, not a random survey of the whole Nation.</p></section><section class="panel"><h3>Optional community-published viewing</h3><p><a href="https://vimeo.com/920504846" target="_blank" rel="noopener">Episode Six – Fish ↗</a><br>James Bay Cree Communications</p><p class="small">${esc(window.WW_READINGS.video)}</p></section></div>`;
if(chapter===1){$('special').innerHTML=`<div class="river-tabs" aria-label="Choose a river">${Object.keys(riverData).map((r,i)=>`<button data-river="${r}" aria-pressed="${i===0}">${r}</button>`).join('')}</div><div id="riverContent" class="river-content"></div><details class="panel"><summary>View original length and mass graphs · Figure 2</summary><a href="assets/study-figure2.png" target="_blank"><img class="figure-img" src="assets/study-figure2.png" alt="Figure 2 from Bowles et al. 2020. Total length in millimetres and mass in grams by river, sex and sampling year; points have 95 percent confidence intervals. The accessible qualitative summaries are above."></a><p class="small">Bowles et al. (2020), Figure 2, p. 1137. Blue: males. Red: females. Vertical bars: 95% confidence intervals. Click to enlarge. These are model-adjusted study means, not simulated fish.</p></details>`;document.querySelectorAll('[data-river]').forEach(b=>b.onclick=()=>showRiver(b.dataset.river));showRiver('Chalifour');}
if(chapter===4){$('special').innerHTML=`<section class="panel"><span class="tag model">Teaching model</span><h2 style="margin-top:15px">Matched-growth comparison</h2><label style="max-width:180px">Comparison seed<input id="growthSeed" type="number" min="1" max="999999" value="42"></label><p class="small">The same 60 fish, at age 6, under three alternative food histories. This comparison is separate from your stream trial.</p><div id="growthCards" class="growth-grid"></div></section>`;$('growthSeed').oninput=growth;growth();}
if(chapter===5){$('special').innerHTML=`<div class="evidence-tabs"><button data-evidence="original" aria-pressed="true">2020 study & debate</button><button data-evidence="later" aria-pressed="false">Later monitoring · 2022</button></div><section id="evidencePanel" class="panel"></section>`;document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>showEvidence(b.dataset.evidence));showEvidence('original');}
if(chapter===6){$('special').innerHTML=`<section class="panel"><h2>Your monitoring plan</h2><p>Choose at least three evidence types. Record your justification in 7.1.</p>${evidenceOptions.map(([title,help],i)=>`<div class="checkrow"><input type="checkbox" id="plan${i}" data-plan="${i}" ${plan.includes(i)?'checked':''}><label for="plan${i}">${title}<small>${help}</small></label></div>`).join('')}<p id="planCount" class="monitor-explain"></p><button id="exportPlan" class="ghost">Download monitoring plan</button></section><blockquote>“${esc(C[0].quote)}”<cite>${esc(C[0].quoteBy)} <button class="linkbutton" data-open-box>Read Box 1</button></cite></blockquote>`;document.querySelectorAll('[data-plan]').forEach(b=>b.onchange=()=>{plan=[...document.querySelectorAll('[data-plan]:checked')].map(x=>+x.dataset.plan);store('plan',plan);planCount();});planCount();$('exportPlan').onclick=()=>download('Walleye_Watch_Monitoring_Plan.txt',plan.map(i=>evidenceOptions[i].join('\n')).join('\n\n')+'\n\nMy explanation:\n'+(notes['7.1']||''),'text/plain');}
document.querySelectorAll('[data-open-box]').forEach(b=>b.onclick=()=>openBox(b));
$('questionFields').innerHTML=c.questions.map(([id,q])=>`<div class="question"><label for="q${id}"><span class="qnum">${id}</span>${esc(q)}</label><textarea id="q${id}" data-note="${id}" placeholder="Record your evidence and reasoning…">${esc(notes[id]||'')}</textarea></div>`).join('');document.querySelectorAll('[data-note]').forEach(x=>x.oninput=()=>{notes[x.dataset.note]=x.value;store('notes',notes);});$('prev').disabled=chapter===0;$('next').disabled=chapter===6;$('next').textContent=chapter===6?'Investigation complete':'Next investigation →';if(!$('lab').hidden)renderLab();}
function go(i){pause();chapter=Math.max(0,Math.min(6,i));location.hash=`chapter-${chapter+1}`;renderChapter();$('main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function showRiver(r){document.querySelectorAll('[data-river]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.river===r)));$('riverContent').innerHTML=`<p class="eyebrow">${riverData[r][0]} · QUALITATIVE SUMMARY</p><h3>${r} River</h3><p>${riverData[r][1]}</p>`;}
function showEvidence(which){document.querySelectorAll('[data-evidence]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.evidence===which)));const later=which==='later',blocks=later?window.WW_READINGS.later:window.WW_READINGS.debate;$('evidencePanel').innerHTML=`<span class="tag ${later?'later':''}">${later?'Later monitoring':'Evidence from the study'}</span><h2 style="margin-top:16px">${later?'Following the fishery over time':'Reading the critique and response'}</h2>${blocks.map(([title,...p])=>`<section class="reading-block"><h3>${esc(title)}</h3>${p.map(t=>`<p>${esc(t)}</p>`).join('')}</section>`).join('')}<p class="small">${later?'<a href="https://fishes-project.ibis.ulaval.ca/wp-content/uploads/sites/16/2022/11/Mistassini-walleye-monitoring-report_final_November-2022.pdf" target="_blank" rel="noopener">Marin & Fraser (2022), monitoring report, pp. 1–7 ↗</a>':'<a href="https://doi.org/10.1111/eva.13122" target="_blank" rel="noopener">Larson et al., critique ↗</a> · <a href="https://doi.org/10.1111/eva.13146" target="_blank" rel="noopener">Bowles et al., response ↗</a>'}</p>`;}
function growth(){const seed=validSeed($('growthSeed').value),f=new M.Model({seed}).fish;$('growthCards').innerHTML=Object.keys(foods).map(food=>{const s=M.stats(f,food);return `<div class="growth-card"><h3>${foods[food]} food</h3><div style="width:${Math.round(s.mean/60*100)}%">${fishSVG}</div><strong>${s.mean.toFixed(1)} cm</strong><p class="small">Mean adult length<br>G frequency: ${(s.p*100).toFixed(1)}%<br>Same 360 allele copies · seed ${seed}</p></div>`;}).join('');}
function planCount(){$('planCount').textContent=`${plan.length} evidence types selected. ${plan.length<3?'Choose at least three and explain their purpose.':'Now explain how they work together and whose priorities guide the inquiry.'}`;}
function validSeed(v){return Math.max(1,Math.min(999999,Math.floor(Number(v)||42)));}
function newTrial(){pause();model=new M.Model({seed:validSeed($('seed').value),mode:$('mode').value,intensity:+$('intensity').value,food:$('food').value});selected=null;$('event').textContent='Generation 1 adults are ready. Apply harvest to begin.';$('runName').value='';$('pending').textContent='New trial started. Changing controls will not alter this trial until Start new trial is clicked.';renderLab();}
function pause(){clearInterval(timer);timer=null;$('stop').disabled=true;$('auto').disabled=model.generation>=6||model.phase==='stopped';$('step').disabled=model.phase==='stopped'||(model.generation>=12&&model.phase==='survivors');}
function takeStep(){const previous=model.phase,old=model.fish.length;model.step();if(previous==='adults')$('event').textContent=`${model.removed.length} of ${old} adults harvested. Inspect the survivors before they reproduce.`;else if(previous==='survivors')$('event').textContent=model.phase==='stopped'?'Reproduction stopped: both female and male parents are needed. Start a new trial.':'60 offspring born. Inspect their parents and alleles before growing them.';else $('event').textContent='The same juveniles have grown to adults. Their alleles did not change during growth.';selected=null;renderLab();if(model.phase==='stopped'||(model.generation>=6&&model.phase==='adults'&&timer))pause();}
function autoRun(){if(model.generation>=6)return;timer=setInterval(takeStep,900);$('stop').disabled=false;$('auto').disabled=true;$('step').disabled=true;}
function genotype(f){return f.genes.map(g=>g.map(a=>a?'G':'g').join('')).join(' · ');}
function renderLab(){const s=M.stats(model.fish,model.settings.food),stage={adults:'Adults before harvest',survivors:'Survivors before reproduction',juveniles:'Juveniles before growth',stopped:'Reproduction stopped'}[model.phase];$('stage').textContent=`Generation ${model.generation} · ${stage}`;$('activeSettings').textContent=`${modes[model.settings.mode]} · ${model.settings.mode==='none'?0:model.settings.intensity}% harvest · ${foods[model.settings.food]} food · seed ${model.settings.seed}`;$('nFish').textContent=s.n;$('mean').textContent=s.mean===null?'—':s.mean.toFixed(1);$('pG').textContent=s.p===null?'—':(s.p*100).toFixed(1)+'%';$('step').textContent={adults:'1 · Apply harvest',survivors:'2 · Reproduce',juveniles:'3 · Grow to adults',stopped:'Start a new trial'}[model.phase];$('step').disabled=!!timer||model.phase==='stopped'||(model.generation>=12&&model.phase==='survivors');$('auto').disabled=!!timer||model.generation>=6||model.phase==='stopped';
$('fishLayer').innerHTML=model.fish.map(f=>`<button class="fish" data-fish="${f.id}" aria-label="Inspect fish ${f.id}, ${M.length(f,model.settings.food)} centimetres" tabindex="-1">${fishSVG}</button>`).join('');visuals=[...document.querySelectorAll('[data-fish]')].map((b,i)=>{const f=model.fish[i];b.style.width=Math.max(26,M.length(f,model.settings.food)*1.25)+'px';b.onclick=()=>inspect(f.id);return {b,id:f.id,base:(i%10)/10,y:.23+Math.floor(i/10)*.113,speed:.013+(f.id%7)*.002,dir:f.id%2?1:-1};});positionFish(0);
$('fishSelect').innerHTML='<option value="">Choose a fish ID…</option>'+model.fish.map(f=>`<option value="${f.id}">Fish ${f.id} · ${M.length(f,model.settings.food)} cm</option>`).join('');if(selected&&model.fish.some(f=>f.id===selected))inspect(selected);else $('fishInfo').textContent=model.phase==='juveniles'?'Choose an offspring to inspect its genotype and parents.':'Click a fish, or choose its ID. All displayed fish are alive.';
$('histogram').innerHTML=histSVG(model.fish,model.settings.food);$('trend').innerHTML=trendSVG(model.history);$('histTable').innerHTML=histTable(model.fish,model.settings.food);$('records').innerHTML=recordsTable();renderSaved();}
function inspect(id){selected=+id;const f=model.fish.find(x=>x.id===selected);if(!f)return;$('fishSelect').value=String(id);document.querySelectorAll('[data-fish]').forEach(b=>b.classList.toggle('selected',+b.dataset.fish===selected));let parents='Founding fish: parents are outside this model.';if(f.parents.length)parents=f.parents.map(id=>{const p=model.lastParents.find(x=>x.id===id);return p?`Parent ${id}: ${genotype(p)}`:`Parent ${id}`;}).join(' | ');$('fishInfo').innerHTML=`<strong>Fish ${f.id}</strong> · ${f.sex==='F'?'Female':'Male'} · Age ${f.age} model years · <strong>${M.length(f,model.settings.food)} cm</strong><br><span class="genes">${genotype(f)}</span> ${M.copies(f)} of 6 copies are G. ${f.age<6?'Not mature yet.':'Eligible to reproduce if it survives.'}<br><span class="small">${parents}</span>`;}
function positionFish(time){const w=$('stream').clientWidth,h=$('stream').clientHeight;visuals.forEach(v=>{const width=parseFloat(v.b.style.width),travel=Math.max(1,w-width-20);const phase=motionPaused?v.base:(v.base+time*.001*v.speed)%1;const x=10+(v.dir===1?phase:1-phase)*travel,y=v.y*h+(motionPaused?0:Math.sin(time*.001+v.id)*7);v.b.style.left=x+'px';v.b.style.top=y+'px';v.b.style.transform=`scaleX(${v.dir})`;});}
function animate(t){if(!$('lab').hidden)positionFish(t);requestAnimationFrame(animate);}
function bins(fish,food){let b=Array(8).fill(0);fish.forEach(f=>b[Math.min(7,Math.max(0,Math.floor(M.length(f,food)/10)))]++);return b;}
function histSVG(fish,food){const b=bins(fish,food),max=Math.max(5,...b),ticks=[0,Math.ceil(max/2),max];return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 440 250" role="img" aria-label="Histogram of current fish length in centimetres. Counts available in the table below."><rect width="440" height="250" fill="#fffefa"/><text x="10" y="17" font-family="sans-serif" font-size="11" fill="#506762">Number of fish</text>${ticks.map(n=>`<line x1="40" y1="${200-n/max*158}" x2="423" y2="${200-n/max*158}" stroke="#d5ded4"/><text x="32" y="${204-n/max*158}" text-anchor="end" font-family="sans-serif" font-size="10">${n}</text>`).join('')}${b.map((v,i)=>`<rect x="${44+i*47}" y="${200-v/max*158}" width="38" height="${v/max*158}" fill="#297e68"/><text x="${63+i*47}" y="216" text-anchor="middle" font-size="9" font-family="sans-serif">${i*10}–${i*10+9}</text>`).join('')}<text x="235" y="240" text-anchor="middle" font-family="sans-serif" font-size="11">Length (cm; bins include decimals below next boundary)</text></svg>`;}
function trendSVG(history){const adult=history.filter(x=>x.phase==='adults'),x=g=>44+(g-1)*33.4,y=p=>202-p*160;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 440 250" role="img" aria-label="G allele frequency in adult cohorts. Values in the stage records."><rect width="440" height="250" fill="#fffefa"/><text x="10" y="17" font-family="sans-serif" font-size="11">G frequency (%) · pooled across three loci</text>${[0,.25,.5,.75,1].map(p=>`<line x1="44" y1="${y(p)}" x2="415" y2="${y(p)}" stroke="#d5ded4"/><text x="35" y="${y(p)+4}" text-anchor="end" font-family="sans-serif" font-size="10">${p*100}</text>`).join('')}<polyline fill="none" stroke="#ab7521" stroke-width="3" points="${adult.map(r=>`${x(r.generation)},${y(r.p)}`).join(' ')}"/>${adult.map(r=>`<circle cx="${x(r.generation)}" cy="${y(r.p)}" r="4" fill="#ab7521"/>`).join('')}${Array.from({length:12},(_,i)=>`<text x="${x(i+1)}" y="217" text-anchor="middle" font-size="10" font-family="sans-serif">${i+1}</text>`).join('')}<text x="230" y="240" text-anchor="middle" font-family="sans-serif" font-size="11">Model generation (adult stage)</text></svg>`;}
function histTable(fish,food){return `<table><caption>Current stage · teaching model</caption><tr><th>Length interval (cm)</th><th>Fish</th></tr>${bins(fish,food).map((v,i)=>`<tr><td>${i*10} to &lt;${(i+1)*10}</td><td>${v}</td></tr>`).join('')}</table>`;}
function recordsTable(){return `<table><caption>Every stage, including survivors and juveniles. Frequencies are percentages.</caption><thead><tr><th>Generation</th><th>Stage</th><th>N</th><th>Mean cm</th><th>G overall %</th><th>Locus 1 %</th><th>Locus 2 %</th><th>Locus 3 %</th></tr></thead><tbody>${model.history.map(r=>`<tr><td>${r.generation}</td><td>${r.phase}</td><td>${r.n}</td><td>${r.mean?.toFixed(1)??'—'}</td><td>${r.p===null?'—':(r.p*100).toFixed(1)}</td>${r.loci.map(p=>`<td>${p===null?'—':(p*100).toFixed(1)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function saveRun(){if(saved.length>=12){$('event').textContent='Twelve runs are already saved. Download them, then remove an old run.';return;}const name=$('runName').value.trim()||`${modes[model.settings.mode]} · ${foods[model.settings.food]} · seed ${model.settings.seed}`;saved.push({name,...model.snapshot()});store('runs',saved);renderSaved();$('event').textContent='Run saved. It is now available in the comparison table.';}
function renderSaved(){$('savedRuns').innerHTML=saved.length?`<table><thead><tr><th>Run</th><th>Generation / stage</th><th>Harvest / food / seed</th><th>Start → saved mean cm</th><th>Start → saved G %</th><th>Remove</th></tr></thead><tbody>${saved.map((r,i)=>{const a=r.history[0],b=r.history.at(-1);return `<tr><td>${esc(r.name)}</td><td>${r.generation} / ${r.phase}</td><td>${modes[r.settings.mode]} (${r.settings.mode==='none'?0:r.settings.intensity}%) / ${foods[r.settings.food]} / ${r.settings.seed}</td><td>${a.mean.toFixed(1)} → ${b.mean?.toFixed(1)??'—'}</td><td>${(a.p*100).toFixed(1)} → ${b.p===null?'—':(b.p*100).toFixed(1)}</td><td><button data-delete="${i}" class="ghost" aria-label="Remove saved run ${esc(r.name)}">×</button></td></tr>`;}).join('')}</tbody></table>`:'<p class="small">No saved runs yet. Save two contrasting trials to compare them here.</p>';document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{saved.splice(+b.dataset.delete,1);store('runs',saved);renderSaved();});}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows){return rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\r\n');}
function exportNotes(){let text='WALLEYE WATCH · FIELD NOTEBOOK\n\n';C.forEach(c=>{text+=c.title+'\n';c.questions.forEach(([id,q])=>text+=`\n${id} ${q}\n${notes[id]||'[No response recorded]'}\n`);text+='\n';});text+='MONITORING PLAN\n'+plan.map(i=>evidenceOptions[i][0]).join('\n');text+='\n\nSAVED RUNS\n'+saved.map(r=>{const s=r.history.at(-1);return `${r.name}: generation ${r.generation} ${r.phase}, ${s.mean?.toFixed(1)} cm, G ${(s.p*100).toFixed(1)}%; seed ${r.settings.seed}`;}).join('\n');download('Walleye_Watch_Notebook.txt',text,'text/plain;charset=utf-8');}
$('newTrial').onclick=newTrial;$('step').onclick=takeStep;$('auto').onclick=autoRun;$('stop').onclick=pause;$('fishSelect').onchange=e=>inspect(+e.target.value);$('saveRun').onclick=saveRun;
$('motion').setAttribute('aria-pressed',String(motionPaused));$('motion').textContent=motionPaused?'Resume fish motion':'Pause fish motion';$('motion').onclick=()=>{motionPaused=!motionPaused;$('motion').setAttribute('aria-pressed',String(motionPaused));$('motion').textContent=motionPaused?'Resume fish motion':'Pause fish motion';};
['mode','food','intensity','seed'].forEach(id=>$(id).onchange=()=>{$('pending').textContent='New settings selected. Click Start new trial to apply them.';$('intensity').disabled=$('mode').value==='none';});$('intensity').disabled=true;
$('downloadCSV').onclick=()=>download('Walleye_Watch_Stages.csv',csv([['kind','seed','harvest','intensity_percent','food','generation','stage','n','mean_cm','G_frequency','locus1_G','locus2_G','locus3_G'],...model.history.map(r=>['Teaching model',model.settings.seed,model.settings.mode,model.settings.mode==='none'?0:model.settings.intensity,model.settings.food,r.generation,r.phase,r.n,r.mean,r.p,...r.loci])]),'text/csv');
$('downloadFish').onclick=()=>download('Walleye_Watch_Fish.csv',csv([['kind','seed','generation','stage','id','sex','age_model_years','length_cm','locus1','locus2','locus3','G_copies','parent1','parent2'],...model.fish.map(f=>['Teaching model',model.settings.seed,model.generation,model.phase,f.id,f.sex,f.age,M.length(f,model.settings.food),...f.genes.map(g=>g.map(a=>a?'G':'g').join('')),M.copies(f),...f.parents])]),'text/csv');
$('downloadRuns').onclick=()=>download('Walleye_Watch_Saved_Runs.json',JSON.stringify({kind:'Teaching model',version:1,runs:saved},null,2),'application/json');
$('downloadGraph').onclick=()=>{const strip=s=>s.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="350" viewBox="0 0 900 350"><rect width="900" height="350" fill="#fffefa"/><text x="20" y="26" font-family="sans-serif" font-size="18">Walleye Watch · Teaching model · Generation ${model.generation} ${model.phase}</text><text x="20" y="51" font-family="sans-serif" font-size="13">${modes[model.settings.mode]} · ${model.settings.mode==='none'?0:model.settings.intensity}% harvest · ${foods[model.settings.food]} food · Seed ${model.settings.seed}</text><g transform="translate(0,70)">${strip(histSVG(model.fish,model.settings.food))}</g><g transform="translate(450,70)">${strip(trendSVG(model.history))}</g></svg>`;download('Walleye_Watch_Graphs.svg',svg,'image/svg+xml');};
$('exportNotes').onclick=exportNotes;$('prev').onclick=()=>go(chapter-1);$('next').onclick=()=>go(chapter+1);
window.addEventListener('hashchange',()=>{const n=+location.hash.replace('#chapter-','');if(n>=1&&n<=7&&chapter!==n-1){pause();chapter=n-1;renderChapter();}});
let boxOpener=null;
function openBox(button){boxOpener=button;$('boxDialog').showModal();$('boxDialog').scrollTop=0;}
$('closeBox').onclick=()=>$('boxDialog').close();$('boxDialog').addEventListener('close',()=>boxOpener?.focus());
$('boxContent').innerHTML=window.WW_READINGS.box.map(([title,text])=>`<section class="box-section"><h3>${esc(title)}</h3>${text.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');
function renderVocabulary(){const q=$('vocabSearch').value.toLowerCase().trim(),entries=Object.entries(window.WW_READINGS.glossary).filter(([term,definition])=>(term+' '+definition).toLowerCase().includes(q));$('vocabList').innerHTML=entries.length?entries.map(([term,definition])=>`<div><dt>${esc(term)}</dt><dd>${esc(definition)}</dd></div>`).join(''):'<p>No matching term. Try another word.</p>';$('vocabCount').textContent=`${entries.length} terms`;}
$('vocabBtn').onclick=()=>{$('vocabDialog').showModal();$('vocabSearch').focus();};$('closeVocab').onclick=()=>$('vocabDialog').close();$('vocabDialog').addEventListener('close',()=>$('vocabBtn').focus());$('vocabSearch').oninput=renderVocabulary;$('vocabDialog').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();$('vocabDialog').close();}});renderVocabulary();
const start=+location.hash.replace('#chapter-','');if(start>=1&&start<=7)chapter=start-1;renderChapter();if(!storageOK)$('storageNotice').textContent='Storage is unavailable. Download your work before leaving.';requestAnimationFrame(animate);
// Read-only inspection hook for deterministic classroom QA.
window.WWTest={get model(){return model;},get saved(){return saved;}};
